CREATE TABLE user_app(
	USER_ID BIGINT PRIMARY KEY AUTO_INCREMENT,
    USER_NAME VARCHAR(200) NOT NULL,
    USER_EMAIL VARCHAR(200) NOT NULL,
    USER_PASSWORD VARCHAR(200) NOT NULL
);

CREATE TABLE card(
	CARD_ID BIGINT PRIMARY KEY AUTO_INCREMENT,
    CARD_NAME VARCHAR(60) NOT NULL,
    CARD_DESCRIPTION VARCHAR(500) NOT NULL,
    CARD_STATUS VARCHAR(5) DEFAULT 'TODO',
    CARD_BLOCKER BIGINT,
    CARD_USER_OWNER BIGINT NOT NULL

    #FOREIGN KEY (CARD_USER_OWNER) REFERENCES user_app(USER_ID),
    #FOREIGN KEY (CARD_BLOCKER) REFERENCES card(CARD_ID)
);

CREATE TABLE authorization(
    AUT_ID BIGINT PRIMARY KEY AUTO_INCREMENT
    AUT_NAME VARCHAR(50) NOT NULL
);

CREATE TABLE user_authorization(
    USER_ID BIGINT,
    AUT_ID BIGINT
);

INSERT INTO authorization(AUT_NAME) VALUES("GOD");
INSERT INTO authorization(AUT_NAME) VALUES("CUSTOMER");